# These are supported funding model platforms
#
github:  # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: raprojects # Replace with a single Open Collective username
#ko_fi: rozanov # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
#buy_me_a_coffee: raprogramm # Replace with a single Buy Me a Coffee username
thanks_dev: # Replace with a single thanks.dev username
custom:
  - "https://etherscan.io/address/0xD653E9c96910D44923027bB0365Ca4A8f580894F"
  - "https://www.blockchain.com/btc/address/bc1qx58y00ljpz0e2anpq90f6uztf0puyuvnq4pcvf"
  - "https://solscan.io/account/GJacUwSi5w9KU8u4fC7XYWYhi6yU6m4dCvmDRmFTbs4R"
